name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which component would this feature affect?
      options:
        - Circuit (Range Check, Sort, Group-By, Join, Aggregation)
        - Prover
        - Database
        - Recursive Proof
        - Optimization
        - SQL Parser
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case for this feature
      placeholder: |
        Example:
        - User wants to verify a complex SQL query with multiple JOINs
        - Need to support additional aggregation functions
        - Performance improvement for large datasets
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes (Optional)
      description: If you have ideas about how this could be implemented, please share
      placeholder: |
        - Technical approach
        - Potential challenges
        - Dependencies needed
      render: markdown

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Any other information that might be helpful...

